# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16a276351067a7cc3c8cdc6e3cb131faa7c4182ece6c8ad2ded53954e810203eaa5a6b084e5dd6f8c790f33f60f2f3403db4618e6ed7903d9ffb0695f49ee04c

test:
  secret_key_base: 2a22f3b0c21d0dc922b10cb593d6ef76b728afaba7b36ff491c8b868a32ef2652fd28d9347317801151c520eec531e60556eb329cd59c7e91a7cf5dea64d7c96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
